### ISSUE TITLE
导入sql后程序运行不起来。

### ISSUE THREAD

**Issue by eaglebetter** [hogenwang/comcms_core#2]
dbconn配的是mysql数据库，模型里面是：[BindTable("Admin", Description = "管理员", ConnName = "dbconn", DbType = DatabaseType.SqlServer)]，不一致么？

**Comment by hogenwang** [comment]
DbType 这个关系不大，主要是ConnName 这个配置对。XCode是ORM。会自动去处理不同数据库的映射关系。所以不用担心这个

**Comment by eaglebetter** [comment]
ok可以了，需要配置的是appsettings.json，而不是app.config。
    "dbconn": {
      "connectionString": "Server=.;Port=3306;Database=comcms2;Uid=root;Pwd=root;",
      "providerName": "MySql.Data.MySqlClient"
    },
